plugins:
  - jekyll-remote-theme

baseurl: "/douglang"
remote_theme: pmarsceill/just-the-docs
title: Douglang Documentation
logo: assets/logo.png

markdown: kramdown

navigation:
  - title: Introduction
    url: /docs/introduction/
  - title: Hey Doug
    url: /docs/hey_doug/
  - title: Variables
    url: /docs/variables
  - title: Control Flow
    url: /docs/control_flow