baseurl: "/douglang"
title: Douglang Documentation

markdown: kramdown

theme: "just-the-docs"

navigation:
  - title: Introduction
    url: /docs/introduction/
  - title: Hey Doug
    url: /docs/hey_doug/
  - title: Variables
    url: /docs/variables
  - title: Control Flow
    url: /docs/control_flow