site_name: Douglang Documentation
docs_dir: docs
site_dir: docs_site
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
nav:
  - 'hey_doug.md'
  - 'variables.md'
  - 'control_flow.md'