name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

        run: |
          gem install bundler
          bundle install

        run: bundle exec jekyll build -d public

        uses: actions/deploy-pages@v1
        with:
          folder: public